version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    scheduler:
      image: apache/airflow
      command: scheduler
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    volumes:
      - pgcb-data:/var/lib/postgresql/data
    # networks:
    #   - postgresql
  etl:
    build: ./etl/
    # restart: always
    command: python3 ./etl/etl.py
    depends_on:
      - db
    # networks:
    #   - postgresql

volumes:
  pgcb-data:

# networks:
#   postgresql:
#     driver: bridge