version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    scheduler:
      image: apache/airflow
      command: scheduler
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    webserver:
      image: apache/airflow
      entrypoint: ./scripts/entrypoint.sh
      restart_policy:
        condition: on-failure
      depends_on:
        - postgres
        - scheduler
      env_file:
        - .env
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./scripts:/opt/airflow/scripts
      ports:
        - "8080:8080"